# Makefile -- UnbloatedPad (Linux/GTK4+libadwaita port of TinyRetroPad), pure x86-64 assembly.
#
# Assembles each src/*.asm with NASM into build/*.o, then links with gcc
# (used purely as the link driver, so we get glibc's CRT startup and
# dynamic linking for free -- GTK/GLib require a fully initialized libc
# anyway). Every line of *our* code is assembly; nothing here is compiled
# from C.

ASM       := nasm
ASMFLAGS  := -f elf64 -g -F dwarf -I src/ -I build/
CC        := gcc

PKGS      := gtk4 libadwaita-1
LIBS      := $(shell /usr/bin/pkg-config --libs $(PKGS) 2>/dev/null)

ifeq ($(strip $(LIBS)),)
$(error pkg-config could not find "$(PKGS)". Install libgtk-4-dev and \
libadwaita-1-dev, and if pkg-config still can't see them, see the \
"Troubleshooting" section in README.md)
endif

SRC_DIR   := src
BUILD_DIR := build
SOURCES   := $(wildcard $(SRC_DIR)/*.asm)
INCLUDES  := $(wildcard $(SRC_DIR)/*.inc)
OBJECTS   := $(patsubst $(SRC_DIR)/%.asm,$(BUILD_DIR)/%.o,$(SOURCES))
TARGET    := upad

# --- version ---------------------------------------------------------
# Single source of truth for upad's version number: the .version file at
# the repo root, not hardcoded here or duplicated in any .asm file. Feeds
# both .deb packaging (DEB_VERSION below) and the About dialog's version
# field (build/version.inc, generated below, %include-d by src/about.asm).
# `$(shell cat ...)` already strips the trailing newline .version ends
# with, same as a shell `$(...)` substitution would.
VERSION := $(shell cat .version)

# --- install layout -----------------------------------------------------
# PREFIX defaults to /usr/local (a local, non-packaged install); the deb
# target below overrides it to /usr, since that's where distro packages
# belong. DESTDIR is the usual staging-root override for packaging.
PREFIX      ?= /usr/local
DESTDIR     ?=
DESKTOP_ID  := org.unbloatedpad.Editor
BIN_DIR     := $(DESTDIR)$(PREFIX)/bin
DESKTOP_DIR := $(DESTDIR)$(PREFIX)/share/applications
ICON_DIR    := $(DESTDIR)$(PREFIX)/share/icons/hicolor/scalable/apps

# --- .deb packaging ---------------------------------------------------
# Runtime deps are the two libraries we link against directly (see $(LIBS)
# above); apt/dpkg resolves their own transitive dependencies (harfbuzz,
# pango, cairo, ...) itself, so those aren't listed here.
DEB_VERSION    := $(VERSION)
DEB_ARCH       := amd64
DEB_MAINTAINER := tiglate <128345445+tiglate@users.noreply.github.com>
DEB_DEPENDS    := libgtk-4-1, libadwaita-1-0
DEB_PKG        := upad_$(DEB_VERSION)_$(DEB_ARCH)
DEB_STAGE      := $(BUILD_DIR)/$(DEB_PKG)

.PHONY: all clean run install uninstall deb release

all: $(TARGET)

# Same binary as `all`, minus the DWARF debug info ASMFLAGS bakes in for
# gdb -- that's the only thing `strip` removes here (it isn't loaded into
# memory at runtime either way, only read by a debugger), so this is a
# pure size win with no behavior change: roughly 115KB -> 49KB as of this
# writing. Always rebuilds from a clean tree first, so the result can't
# accidentally be a stripped copy of a stale/partial build.
release: clean $(TARGET)
	strip --strip-all $(TARGET)
	@echo "Stripped release build: $(TARGET) ($$(ls -lh $(TARGET) | awk '{print $$5}')B)"

$(TARGET): $(OBJECTS)
	$(CC) -o $@ $^ $(LIBS)

$(BUILD_DIR)/%.o: $(SRC_DIR)/%.asm $(INCLUDES) | $(BUILD_DIR)
	$(ASM) $(ASMFLAGS) -o $@ $<

# Generated, not hand-written -- see the VERSION comment above. Lives under
# build/ (gitignored) rather than src/, same reasoning as every other build
# artifact: it's derived, not authored. Only about.o actually needs it (see
# the extra prerequisite line right below), but it's cheap enough to not
# bother scoping the rule any tighter than "regenerate whenever .version changes".
$(BUILD_DIR)/version.inc: .version | $(BUILD_DIR)
	printf '; version.inc -- auto-generated by the Makefile from .version; do not edit directly.\nsection .rodata\nversion_str  db "%s", 0\n' "$(VERSION)" > $@

$(BUILD_DIR)/about.o: $(BUILD_DIR)/version.inc

$(BUILD_DIR):
	mkdir -p $(BUILD_DIR)

run: $(TARGET)
	./$(TARGET)

# Installs the binary, .desktop launcher, and icon (into the hicolor icon
# theme, named after DESKTOP_ID so icon-theme lookups by app-id -- see
# window.asm's gtk_window_set_icon_name call -- and this project's own
# Icon= key both resolve to it). `make install PREFIX=/usr` for a
# system-wide (as opposed to /usr/local) install. Note this is NOT needed
# just to see the icon in a `make && ./upad` dev build -- window.asm finds
# icons/hicolor itself, relative to the built binary, without installing.
# Depends on `release`, not `$(TARGET)` directly, so anything actually
# installed is always the stripped build, never a leftover debug one.
install: release
	install -Dm755 $(TARGET) $(BIN_DIR)/$(TARGET)
	install -Dm644 $(DESKTOP_ID).desktop $(DESKTOP_DIR)/$(DESKTOP_ID).desktop
	install -Dm644 icons/hicolor/scalable/apps/$(DESKTOP_ID).svg $(ICON_DIR)/$(DESKTOP_ID).svg

uninstall:
	rm -f $(BIN_DIR)/$(TARGET) $(DESKTOP_DIR)/$(DESKTOP_ID).desktop $(ICON_DIR)/$(DESKTOP_ID).svg

# Stages the same install tree (via `install` above, rooted at DEB_STAGE
# with PREFIX=/usr) plus DEBIAN/control metadata, and packs it with
# dpkg-deb. Install with `sudo apt install ./$(DEB_PKG).deb` (plain
# `dpkg -i` won't pull in DEB_DEPENDS automatically). No prerequisite of
# its own -- the `$(MAKE) install` call below depends on `release`,
# which is what actually (re)builds and strips $(TARGET); adding another
# `release`/`$(TARGET)` prerequisite here would just rebuild it twice.
deb:
	rm -rf $(DEB_STAGE)
	$(MAKE) install DESTDIR=$(DEB_STAGE) PREFIX=/usr
	mkdir -p $(DEB_STAGE)/DEBIAN $(DEB_STAGE)/usr/share/doc/upad
	install -m644 LICENSE $(DEB_STAGE)/usr/share/doc/upad/copyright
	printf 'Package: upad\nVersion: %s\nSection: editors\nPriority: optional\nArchitecture: %s\nDepends: %s\nMaintainer: %s\nDescription: A classic Notepad-style text editor\n Linux/GTK4+libadwaita port of TinyRetroPad, written entirely in\n hand-written x86-64 assembly.\n' \
	    "$(DEB_VERSION)" "$(DEB_ARCH)" "$(DEB_DEPENDS)" "$(DEB_MAINTAINER)" \
	    > $(DEB_STAGE)/DEBIAN/control
	dpkg-deb --build --root-owner-group $(DEB_STAGE) $(DEB_PKG).deb
	@echo "Built $(DEB_PKG).deb"

clean:
	rm -rf $(BUILD_DIR) $(TARGET) upad_*.deb
