; about.asm -- Help > About UnbloatedPad, via AdwAboutDialog (libadwaita
; 1.5+; this build links against 1.5.0).
;
; UnbloatedPad is the Linux/GTK4+libadwaita port of TinyRetroPad (the
; original Win32/MASM project by Dave Plummer and Matt Power). This port
; was written by Tiglate Pileser III (tiglate) with Claude (Anthropic)
; doing the actual assembly authoring under his direction -- see the
; About dialog built below and linux/README.md for the same credit.

%include "consts.inc"    ; GTK_LICENSE_APACHE_2_0
%include "callconv.inc"  ; CCALL macro + calling-convention discipline
%include "extern.inc"    ; extern declarations for every GTK/Adw call used below
%include "version.inc"   ; build/version.inc, generated by the Makefile from .version -- declares version_str, used below by adw_about_dialog_set_version

global on_about_activate      ; the "win.about" GAction handler, called from actions.asm's win_actions table
global on_view_help_activate  ; the "win.view-help" GAction handler, called from actions.asm's win_actions table

extern g_window                 ; main window (main.asm/window.asm) -- About is presented as a child of it, and passed as GtkUriLauncher's parent

section .rodata
    ; this port's own GitHub repo (as opposed to website_str above, which
    ; deliberately points at the original Windows TinyRetroPad this was
    ; ported from) -- what Help > View Help opens
    help_url_str  db "https://github.com/tiglate/upad", 0
    ; AdwAboutDialog text fields. Every one of these is just a plain
    ; NUL-terminated C string handed to a dedicated setter -- no string
    ; formatting/concatenation needed anywhere in this file.
    app_name_str  db "UnbloatedPad", 0
    dev_name_str  db "Tiglate Pileser III (tiglate)", 0
    ; version_str itself comes from version.inc (%include-d above), not
    ; declared here -- see the .version file at the repo root
    comments_str  db "A pure x86-64 assembly recreation of classic Notepad for Linux, built directly on the GTK4 and libadwaita C ABI (no C glue code). This Linux port was created by Tiglate Pileser III (tiglate) using Claude (Anthropic) as the assembly author, based on the original Win32/MASM TinyRetroPad.", 0
    website_str   db "https://github.com/davepl/TinyRetroPad", 0

    ; "Original Windows Edition" credit section: adw_about_dialog_add_credit_section
    ; wants a NULL-terminated array of "Name" (or "Name <email>") strings,
    ; not a single blob, so the two author names are separate C strings...
    credit_name_1 db "Dave Plummer", 0
    credit_name_2 db "Matt Power", 0
    credit_section_title db "Original Windows Edition (TinyRetroPad)", 0

section .data
    align 8
    ; ...referenced from this array, which is what actually gets passed as
    ; the "const char **people" argument. The trailing 0 is the required
    ; NULL terminator that tells GTK where the list of names ends.
    credit_people:
        dq credit_name_1
        dq credit_name_2
        dq 0

section .text

; void on_about_activate(GSimpleAction *action, GVariant *parameter, gpointer user_data)
;
; Builds a fresh AdwAboutDialog every time (About is opened rarely enough
; that there's no benefit to caching/reusing one, unlike e.g. the Font
; dialog which the user might reopen repeatedly) and immediately shows it.
on_about_activate:
    push rbp       ; save caller's frame pointer
    mov  rbp, rsp  ; establish our own frame
    sub  rsp, 16   ; reserve one 8-byte local slot (16 for alignment): [rbp-8] = the AdwAboutDialog* we're building

    ; --- construct the dialog object ---------------------------------
    CCALL adw_about_dialog_new  ; AdwDialog *adw_about_dialog_new(void) -- rax = new dialog, owned by us until we hand it to adw_dialog_present below
    mov  [rbp-8], rax           ; stash it -- every field-setter call below will clobber rax via its own CCALL

    ; --- fill in the informational fields, one setter call each ------
    mov  rdi, [rbp-8]             ; arg1 = self (the dialog)
    lea  rsi, [rel app_name_str]  ; arg2 = "UnbloatedPad"
    CCALL adw_about_dialog_set_application_name

    mov  rdi, [rbp-8]             ; reload self -- rdi is caller-saved, the previous CCALL may have clobbered it
    lea  rsi, [rel dev_name_str]  ; "Tiglate Pileser III (tiglate)" -- the Linux port's author
    CCALL adw_about_dialog_set_developer_name

    mov  rdi, [rbp-8]
    lea  rsi, [rel version_str]           ; the .version file's contents (e.g. "0.1.0"), embedded at build time -- see build/version.inc
    CCALL adw_about_dialog_set_version

    mov  rdi, [rbp-8]
    lea  rsi, [rel comments_str]          ; long-form description, incl. the AI-assisted-authorship note
    CCALL adw_about_dialog_set_comments

    mov  rdi, [rbp-8]
    lea  rsi, [rel website_str]           ; upstream project repo (the original Windows TinyRetroPad this is ported from)
    CCALL adw_about_dialog_set_website

    mov  rdi, [rbp-8]
    mov  esi, GTK_LICENSE_APACHE_2_0      ; matches the Apache-2.0 LICENSE.TXT this whole repository (Windows original + this port) ships under
    CCALL adw_about_dialog_set_license_type

    ; --- add a separate credit section naming the original authors ---
    mov  rdi, [rbp-8]                     ; self
    lea  rsi, [rel credit_section_title]  ; "Original Windows Edition (TinyRetroPad)"
    lea  rdx, [rel credit_people]         ; NULL-terminated {Dave Plummer, Matt Power, NULL} array built above
    CCALL adw_about_dialog_add_credit_section

    ; --- show it, parented to the main window -------------------------
    mov  rdi, [rbp-8]         ; self
    mov  rsi, [rel g_window]  ; parent -- AdwDialog presents itself modally/as-a-sheet relative to this window
    CCALL adw_dialog_present

    leave  ; mov rsp, rbp; pop rbp -- tear down our frame
    ret    ; back to whatever invoked the "about" action (GTK's action-activation machinery)

; void on_view_help_activate(GSimpleAction *action, GVariant *parameter, gpointer user_data)
; Help > View Help: opens this project's GitHub repo in the user's default
; browser via GtkUriLauncher (GTK 4.10+, async -- same shape as
; fileio.asm's GtkFileDialog calls: show/launch and return immediately,
; the real "did it work" callback fires later).
on_view_help_activate:
    push rbp
    mov  rbp, rsp
    sub  rsp, 16                  ; [rbp-8] = the GtkUriLauncher object, needed across the two calls below

    lea  rdi, [rel help_url_str]  ; arg1 = uri
    CCALL gtk_uri_launcher_new    ; GtkUriLauncher *gtk_uri_launcher_new(const char *uri) -- rax = new launcher, owned by us until handed off below
    mov  [rbp-8], rax

    mov  rdi, [rbp-8]                      ; arg1 = self
    mov  rsi, [rel g_window]               ; arg2 = parent
    xor  edx, edx                          ; arg3 = cancellable = NULL
    lea  rcx, [rel on_view_help_finished]  ; arg4 = callback
    xor  r8, r8                            ; arg5 = user_data = NULL
    CCALL gtk_uri_launcher_launch          ; void gtk_uri_launcher_launch(GtkUriLauncher*, GtkWindow*, GCancellable*, GAsyncReadyCallback, gpointer) -- shows/launches, returns immediately

    mov  rdi, [rbp-8]
    CCALL g_object_unref                             ; drop our reference -- the async op holds its own ref while running, same reasoning as fileio.asm's file-dialog calls

    leave
    ret

; void on_view_help_finished(GObject *source, GAsyncResult *res, gpointer user_data)
; The GAsyncReadyCallback for gtk_uri_launcher_launch above. There's
; nothing useful to do differently on success vs. failure (no dialog is
; more actionable than "the browser either opened or it didn't"), but the
; _finish call still has to be made to release the async operation's
; internal resources.
on_view_help_finished:
    push rbp
    mov  rbp, rsp
    ; source (rdi) and res (rsi) already positioned correctly for the
    ; *_finish(self, result, error) call, same reasoning as fileio.asm's
    ; on_open_finished
    xor  edx, edx                         ; arg3 = error = NULL, ignored
    CCALL gtk_uri_launcher_launch_finish  ; gboolean gtk_uri_launcher_launch_finish(GtkUriLauncher*, GAsyncResult*, GError**) -- return value ignored
    pop  rbp
    ret
